version: 2

project_name: PortKiller

builds:
  - env: [CGO_ENABLED=0]
    goos: [linux]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w
      - -X PortKiller/internal/version.Version={{.Version}}
      - -X PortKiller/internal/version.Commit={{.ShortCommit}}
      - -X PortKiller/internal/version.Date={{.Date}}

archives:
  - formats: [tar.gz]


checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc